sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec spec
after_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi

